### ISSUE TITLE
Can't create customer 

### ISSUE THREAD

**Issue by bshiroya** [magja/magja#115]
Exception in thread "main" com.google.code.magja.service.ServiceException: Customer email is required
	at com.google.code.magja.service.customer.CustomerRemoteServiceImpl.save(CustomerRemoteServiceImpl.java:190)
	at com.google.code.magja.service.cart.MyProd.main(MyProd.java:46)

**Comment by zambrovski** [comment]
Hi,

I think this is indeed a required field.

Can you post your code here?

**Comment by bshiroya** [comment]
```
package com.google.code.magja.service.cart;

import java.util.List;

import com.google.code.magja.model.cart.Cart;
import com.google.code.magja.model.customer.Customer;
import com.google.code.magja.model.customer.CustomerAddress;
import com.google.code.magja.model.customer.Customer.Gender;
import com.google.code.magja.model.product.Product;
import com.google.code.magja.service.RemoteServiceFactory;
import com.google.code.magja.service.customer.CustomerAddressRemoteService;
import com.google.code.magja.service.customer.CustomerRemoteService;
import com.google.code.magja.service.product.ProductRemoteService;
import com.google.code.magja.soap.MagentoSoapClient;
import com.google.code.magja.soap.SoapConfig;
import com.google.code.magja.utils.MagjaStringUtils;

public class Local {
	public static void main(String[] args) throws Exception {

		String apiUser = "rahul";
		String apiKey = "agile@123";
		String remoteHost = "http://192.168.1.241:81/magento/api/soap/";

		SoapConfig soapConfig = new SoapConfig(apiUser, apiKey, remoteHost);
		MagentoSoapClient magentoSoapClient = new MagentoSoapClient(soapConfig);
		final RemoteServiceFactory remoteServiceFactory = new RemoteServiceFactory(magentoSoapClient);
		CustomerRemoteService customerService = remoteServiceFactory.getCustomerRemoteService();
		/*
		 * CustomerAddressRemoteService customerAddressService =
		 * remoteServiceFactory.getCustomerAddressRemoteService();
		 * CartRemoteService service =
		 * remoteServiceFactory.getCartRemoteService(); ProductRemoteService
		 * productService = remoteServiceFactory.getProductRemoteService();
		 */

		Customer cust = new Customer();

		cust.setFirstName(MagjaStringUtils.randomString(5, 10));
		cust.setMiddleName(MagjaStringUtils.randomString(5, 10));
		cust.setLastName(MagjaStringUtils.randomString(5, 10));
		cust.setPassword("test12");
		cust.setPrefix("Mr.");
		cust.setWebsiteId(1);
		cust.setGroupId(1);
		cust.setGender(Gender.MALE);
		String email = MagjaStringUtils.randomString(4, 5) + "@" + MagjaStringUtils.randomString(4, 5) + ".com";
		cust.setEmail(email.toLowerCase());
		cust.set("dob", "1980-08-17 20:53:04");

		
		customerService.save(cust);
		/*
		 * Customer customer=customerService.getById(7); List<CustomerAddress>
		 * customerAddresses=customerAddressService.list(7); for
		 * (CustomerAddress customerAddress : customerAddresses) {
		 * System.out.println(customerAddress.getDefaultShipping());
		 * System.out.println(customerAddress.getDefaultBilling()); }
		 * 
		 * Product product=productService.getById(4);
		 * System.out.println(product.getWebsites());
		 */

	}
}

```

**Comment by bshiroya** [comment]
```
package com.google.code.magja.service.cart;

import java.util.List;

import com.google.code.magja.model.cart.Cart;
import com.google.code.magja.model.customer.Customer;
import com.google.code.magja.model.customer.CustomerAddress;
import com.google.code.magja.model.customer.Customer.Gender;
import com.google.code.magja.model.product.Product;
import com.google.code.magja.service.RemoteServiceFactory;
import com.google.code.magja.service.customer.CustomerAddressRemoteService;
import com.google.code.magja.service.customer.CustomerRemoteService;
import com.google.code.magja.service.product.ProductRemoteService;
import com.google.code.magja.soap.MagentoSoapClient;
import com.google.code.magja.soap.SoapConfig;
import com.google.code.magja.utils.MagjaStringUtils;

public class Local {
	public static void main(String[] args) throws Exception {

		String apiUser = "rahul";
		String apiKey = "agile@123";
		String remoteHost = "http://192.168.1.241:81/magento/api/soap/";

		SoapConfig soapConfig = new SoapConfig(apiUser, apiKey, remoteHost);
		MagentoSoapClient magentoSoapClient = new MagentoSoapClient(soapConfig);
		final RemoteServiceFactory remoteServiceFactory = new RemoteServiceFactory(magentoSoapClient);
		CustomerRemoteService customerService = remoteServiceFactory.getCustomerRemoteService();

		Customer cust = new Customer();

		cust.setFirstName(MagjaStringUtils.randomString(5, 10));
		cust.setMiddleName(MagjaStringUtils.randomString(5, 10));
		cust.setLastName(MagjaStringUtils.randomString(5, 10));
		cust.setPassword("test12");
		cust.setPrefix("Mr.");
		cust.setWebsiteId(1);
		cust.setGroupId(1);
		cust.setGender(Gender.MALE);
		String email = MagjaStringUtils.randomString(4, 5) + "@" + MagjaStringUtils.randomString(4, 5) + ".com";
		cust.setEmail(email.toLowerCase());
		cust.set("dob", "1980-08-17 20:53:04");

		customerService.save(cust);

	}
}

```
-----------------------------------------------------Output-------------------------------------------------
15:49:07 [main] INFO  c.g.c.magja.soap.MagentoSoapClient - ====================================== Logging in user: rahul
15:49:08 [main] INFO  c.g.c.magja.soap.MagentoSoapClient - ====================================== Logged in sessionId: 6f7c5bc71adda7a871c9db610c09475a
15:49:08 [main] INFO  c.g.c.magja.soap.MagentoSoapClient - Calling customer.create [[{firstname=xjjiwudapt, gender=1, group_id=1, dob=1980-08-17 20:53:04, prefix=Mr., password_hash=60474c9c10d7142b7508ce7a50acf414, middlename=llcjlcz, website_id=1, email=oznh@zwute.com, lastname=upercuuou}]] at rahul@http://192.168.1.241:81/magento/api/soap/ with session 6f7c5bc71adda7a871c9db610c09475a
Exception in thread "main" com.google.code.magja.service.ServiceException: Customer email is required
	at com.google.code.magja.service.customer.CustomerRemoteServiceImpl.save(CustomerRemoteServiceImpl.java:190)
	at com.google.code.magja.service.cart.Local.main(Local.java:52)

**Comment by bshiroya** [comment]
any update  ?

**Comment by bshiroya** [comment]
Test Case Result

`com.google.code.magja.service.ServiceException: Customer email is required
	at com.google.code.magja.service.customer.CustomerRemoteServiceImpl.save(CustomerRemoteServiceImpl.java:190)
	at com.google.code.magja.service.customer.CustomerRemoteServiceITest.testSave(CustomerRemoteServiceITest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

`

**Comment by bshiroya** [comment]
help ?

**Comment by zambrovski** [comment]
I’ll have a look on it tomorrow

**Comment by guimaraessilas** [comment]
same problem to me

**Comment by bshiroya** [comment]
@guimaraessilas  i was fixed dude

**Comment by bshiroya** [comment]
Contact me skype: bhadresh.shiroya12

**Comment by bshiroya** [comment]
@guimaraessilas  Contact me skype: bhadresh.shiroya12
