### ISSUE TITLE
32 - Product update error 

### ISSUE THREAD

**Issue by ceefour** [magja/magja#32]
<pre>
<b>What steps will reproduce the problem?</b>
1. Load a simple or grouped product
2. Modify an attribute or not
3. save it

<b>What is the expected output? What do you see instead?</b>
Exception :
java.lang.RuntimeException: keyValue not implemented for class java.util.LinkedList
        at com.google.code.magja.soap.SoapCallFactory.typedElement(SoapCallFactory.java:183)
        at com.google.code.magja.soap.SoapCallFactory.keyValue(SoapCallFactory.java:212)
        at com.google.code.magja.soap.SoapCallFactory.typedElement(SoapCallFactory.java:179)
        at com.google.code.magja.soap.SoapCallFactory.createCall(SoapCallFactory.java:108)
        at com.google.code.magja.soap.MagentoSoapClient.call(MagentoSoapClient.java:102)
        at com.google.code.magja.service.product.ProductRemoteServiceImpl.save(ProductRemoteServiceImpl.java:420)

<b>What version of the product are you using? On what operating system?</b>
Current snapshot.

</pre></br>Original link: http://code.google.com/p/magja/issues/detail?id=32

**Comment by zambrovski** [comment]
Housekeeping: stale issue closed.
